import { Question } from "./types";

export const questions: Question[] = [
  {
    id: 1,
    text: "What do you think life is all about?",
    type: "radio-text",
    options: [
      "A journey of purpose",
      "Living for God",
      "Enjoying every moment",
      "Building a legacy",
      "A test for the afterlife",
      "Survival and success",
    ],
    required: true,
  },
  {
    id: 2,
    text: "What skill do you have interest in?",
    type: "radio-text",
    options: [
      "Music / Instrument",
      "Coding / Technology",
      "Sports / Athletics",
      "Fashion / Design",
      "Writing / Content Creation",
      "Business / Entrepreneurship",
      "Speaking / Communication",
      "Art / Creative Arts",
    ],
    required: true,
  },
  {
    id: 3,
    text: "What is your greatest regret?",
    type: "textarea",
    placeholder: "Share honestly... no one will judge you here",
    required: true,
  },
  {
    id: 4,
    text: "Who is your role model?",
    type: "radio-text",
    options: [
      "My parent / guardian",
      "A pastor / religious leader",
      "A teacher / mentor",
      "A public figure / celebrity",
      "Jesus Christ",
      "My sibling / friend",
    ],
    required: true,
  },
  {
    id: 5,
    text: "Honestly! Are you born again?",
    type: "radio",
    options: [
      "Yes, I am born again",
      "No, but I want to be",
      "No, and I'm not ready yet",
      "I'm not sure what that means",
    ],
    required: true,
  },
  {
    id: 6,
    text: "What is your greatest fear?",
    type: "textarea",
    placeholder: "Share what's on your heart...",
    required: true,
  },
  {
    id: 7,
    text: "Why haven't you joined the teens church workers?",
    type: "radio-text",
    options: [
      "I'm not ready spiritually",
      "I don't have enough time",
      "I haven't been invited or asked",
      "I'm shy / not confident enough",
      "I don't fully understand what it means",
      "I'm already a church worker!",
      "I'm not interested",
    ],
    required: true,
  },
  {
    id: 8,
    text: "Are you in a relationship?",
    type: "radio",
    options: [
      "Yes, I am in a relationship",
      "No, I'm single",
      "I'm not sure",
      "Prefer not to say",
    ],
    required: true,
  },
  {
    id: 9,
    text: "What do you know about the Gospel of Jesus Christ?",
    type: "textarea",
    placeholder: "Share your understanding in your own words...",
    required: true,
  },
  {
    id: 10,
    text: "Is anybody threatening you in any way? (You can share here, no one will know)",
    type: "radio-text",
    options: [
      "No, I'm safe",
      "Yes, I'm being bullied at school",
      "Yes, someone is threatening me",
      "I'd rather not say",
    ],
    required: true,
  },
  {
    id: 11,
    text: "Do you know your talent, or something you are good at and love doing?",
    type: "radio-text",
    options: [
      "Yes, I know my talent clearly",
      "I have an idea but I'm not sure",
      "No, I'm still discovering myself",
      "I don't think I have any special talent",
    ],
    required: true,
  },
  {
    id: 12,
    text: "How do you envision yourself in the next five years?",
    type: "textarea",
    placeholder: "Describe your dream future...",
    required: true,
  },
  {
    id: 13,
    text: "Do you believe God is interested in making you rich?",
    type: "radio",
    options: [
      "Yes, God wants me to prosper",
      "No, God cares more about my soul than money",
      "Maybe, but I'm not sure",
      "I don't know / haven't thought about it",
    ],
    required: true,
  },
  {
    id: 14,
    text: "Has Jesus ever spoken to you before?",
    type: "radio-text",
    options: [
      "Yes, I've heard His voice",
      "I think so but I'm not sure",
      "No, never",
      "I don't believe in that",
    ],
    required: true,
  },
  {
    id: 15,
    text: "If you had an opportunity to master a skill that would profit you greatly in the nearest future, how serious would you be?",
    type: "radio-text",
    options: [
      "I'd be fully committed — 100%",
      "I'd give it my very best",
      "I'd try but can't make promises",
      "I'm not interested in skills",
    ],
    required: true,
  },
  {
    id: 16,
    text: "Are you willing to sacrifice social media to love God and work on yourself?",
    type: "radio",
    options: [
      "Yes, completely — I'm ready",
      "I'd reduce it significantly",
      "I'd try but it's very hard",
      "No, I can't do that",
    ],
    required: true,
  },
];
